"""run models

Revision ID: 0424a3ac23d8
Revises: ddf6a1ca905c
Create Date: 2025-02-10 23:39:57.105138

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0424a3ac23d8'
down_revision = 'ddf6a1ca905c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classification_results', sa.Column('run_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('classification_results', sa.Column('run_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint('classification_results_document_id_fkey', 'classification_results', type_='foreignkey')
    op.create_foreign_key(None, 'classification_results', 'document', ['document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classification_results', type_='foreignkey')
    op.create_foreign_key('classification_results_document_id_fkey', 'classification_results', 'document', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_column('classification_results', 'run_description')
    op.drop_column('classification_results', 'run_name')
    # ### end Alembic commands ###
