"""Remove user_id from documents

Revision ID: 08335d716b81
Revises: 8e9f078129f7
Create Date: 2025-02-04 14:02:03.625028

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '08335d716b81'
down_revision = '8e9f078129f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savedresultset',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('scheme_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classificationresult',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['classificationscheme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classificationresult')
    op.drop_table('savedresultset')
    # ### end Alembic commands ###
