"""Remove user_id from documents

Revision ID: 18b7febba100
Revises: 08335d716b81
Create Date: 2025-02-04 14:02:15.479044

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '18b7febba100'
down_revision = '08335d716b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
