"""Link documents to workspaces and users

Revision ID: 1e8c0f1e6903
Revises: 3bcaaf8c94f3
Create Date: 2025-01-28 12:27:59.253236

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1e8c0f1e6903'
down_revision = '3bcaaf8c94f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.add_column('document', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'document', 'workspace', ['workspace_id'], ['uid'])
    op.create_foreign_key(None, 'document', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_column('document', 'user_id')
    op.drop_column('document', 'workspace_id')
    # ### end Alembic commands ###
