"""files new

Revision ID: 273431e58eae
Revises: 9cdccaced0eb
Create Date: 2025-02-08 01:34:36.147850

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '273431e58eae'
down_revision = '9cdccaced0eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('top_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('file', sa.Column('media_type', sa.Text(), nullable=True))
    op.alter_column('file', 'top_image',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('file', 'flags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('flags', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('file', 'top_image',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('file', 'media_type')
    op.drop_column('document', 'top_image')
    # ### end Alembic commands ###
