"""Adding files to documents

Revision ID: 32b80edb5df0
Revises: f369bc09c091
Create Date: 2025-02-13 08:00:23.008382

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '32b80edb5df0'
down_revision = 'f369bc09c091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
