"""Changing file endpoints

Revision ID: 331a955c4d88
Revises: 110b0a6d05d3
Create Date: 2025-02-07 02:18:37.413588

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '331a955c4d88'
down_revision = '110b0a6d05d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
