"""file

Revision ID: 34c94ba9c6d4
Revises: 32b80edb5df0
Create Date: 2025-02-14 11:40:18.831441

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '34c94ba9c6d4'
down_revision = '32b80edb5df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
