"""Adding files to documents

Revision ID: 39ee63f147de
Revises: 0424a3ac23d8
Create Date: 2025-02-11 02:39:38.341770

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '39ee63f147de'
down_revision = '0424a3ac23d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
