"""file

Revision ID: 4d3fb6d39a23
Revises: 34c94ba9c6d4
Create Date: 2025-02-14 11:41:39.453933

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4d3fb6d39a23'
down_revision = '34c94ba9c6d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
