"""CRUD for Classification Schemes

Revision ID: 51acd2846fd9
Revises: 777e1181d1b5
Create Date: 2025-01-28 03:42:12.418325

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '51acd2846fd9'
down_revision = '777e1181d1b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
