"""media details

Revision ID: 53b2f1dd9870
Revises: cf26d5679078
Create Date: 2025-02-08 00:42:34.570451

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '53b2f1dd9870'
down_revision = 'cf26d5679078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('caption', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('file', sa.Column('is_primary_image', sa.Boolean(), nullable=False))
    op.add_column('file', sa.Column('media_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('file', sa.Column('video_frame_data', sa.JSON(), nullable=True))
    op.add_column('file', sa.Column('image_analysis', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'image_analysis')
    op.drop_column('file', 'video_frame_data')
    op.drop_column('file', 'media_type')
    op.drop_column('file', 'is_primary_image')
    op.drop_column('file', 'caption')
    # ### end Alembic commands ###
