"""Adding files to documents

Revision ID: 56e2f2e2c3b3
Revises: be67d49d95be
Create Date: 2025-02-13 03:43:58.110155

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '56e2f2e2c3b3'
down_revision = 'be67d49d95be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
