"""Remove user_id from documents

Revision ID: 6fb284720df8
Revises: ae71fcf88aca
Create Date: 2025-02-04 21:38:29.570337

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6fb284720df8'
down_revision = 'ae71fcf88aca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
