"""CRUD for Classification Schemes

Revision ID: 777e1181d1b5
Revises: ddfd83e6739e
Create Date: 2025-01-28 03:27:39.476571

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '777e1181d1b5'
down_revision = 'ddfd83e6739e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
