"""Add icon to workspaces

Revision ID: 850753065dfc
Revises: cb1a7163e62b
Create Date: 2025-01-28 16:08:05.959088

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '850753065dfc'
down_revision = 'cb1a7163e62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
