"""Remove user_id from documents

Revision ID: 8e9f078129f7
Revises: b752a1f38a18
Create Date: 2025-01-29 01:30:08.526922

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8e9f078129f7'
down_revision = 'b752a1f38a18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
