"""Adding files to documents

Revision ID: 9c05fb404c12
Revises: 331a955c4d88
Create Date: 2025-02-07 02:46:27.527478

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9c05fb404c12'
down_revision = '331a955c4d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
