"""dates

Revision ID: 9c81b05cbbe1
Revises: 228a401f51df
Create Date: 2025-02-14 12:19:08.391225

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9c81b05cbbe1'
down_revision = '228a401f51df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
