"""files

Revision ID: 9cdccaced0eb
Revises: 53b2f1dd9870
Create Date: 2025-02-08 00:50:13.402752

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9cdccaced0eb'
down_revision = '53b2f1dd9870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('caption', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('file', sa.Column('flags', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('file', sa.Column('top_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'top_image')
    op.drop_column('file', 'flags')
    op.drop_column('file', 'caption')
    # ### end Alembic commands ###
