"""Remove user_id from documents

Revision ID: ae71fcf88aca
Revises: f8e21c6e0ecf
Create Date: 2025-02-04 20:57:27.038227

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ae71fcf88aca'
down_revision = 'f8e21c6e0ecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
