"""Add icon to workspaces

Revision ID: b752a1f38a18
Revises: 850753065dfc
Create Date: 2025-01-28 16:08:40.725333

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b752a1f38a18'
down_revision = '850753065dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
