"""Adding files to documents

Revision ID: be67d49d95be
Revises: c55de9708009
Create Date: 2025-02-13 02:45:51.031863

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'be67d49d95be'
down_revision = 'c55de9708009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
