"""Add icon to workspaces

Revision ID: cb1a7163e62b
Revises: 1e8c0f1e6903
Create Date: 2025-01-28 15:36:36.395280

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cb1a7163e62b'
down_revision = '1e8c0f1e6903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace', sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace', 'icon')
    # ### end Alembic commands ###
