"""Files Ugh..

Revision ID: cf26d5679078
Revises: a7f43886af1f
Create Date: 2025-02-07 13:54:43.761541

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cf26d5679078'
down_revision = 'a7f43886af1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
