"""files

Revision ID: ddf6a1ca905c
Revises: f85e8315779c
Create Date: 2025-02-10 15:27:17.009612

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ddf6a1ca905c'
down_revision = 'f85e8315779c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
