"""CRUD for Classification Schemes

Revision ID: ddfd83e6739e
Revises: cd4e15127706
Create Date: 2025-01-28 03:20:56.556253

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ddfd83e6739e'
down_revision = 'cd4e15127706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
