"""Add classification_schemes table

Revision ID: f2a3580fe700
Revises: 0df46601c2c9
Create Date: 2025-01-28 01:38:56.148353

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f2a3580fe700'
down_revision = '0df46601c2c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
