"""Adding files to documents

Revision ID: f369bc09c091
Revises: 3863560b6a9e
Create Date: 2025-02-13 06:18:30.147734

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f369bc09c091'
down_revision = '3863560b6a9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classificationscheme', sa.Column('max_labels', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classificationscheme', 'max_labels')
    # ### end Alembic commands ###
