"""files

Revision ID: f85e8315779c
Revises: f8eef4bc0519
Create Date: 2025-02-08 15:56:11.843583

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f85e8315779c'
down_revision = 'f8eef4bc0519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
