"""Remove user_id from documents

Revision ID: f8e21c6e0ecf
Revises: 11feee2dbc91
Create Date: 2025-02-04 20:30:50.335640

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f8e21c6e0ecf'
down_revision = '11feee2dbc91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
