"""filesx

Revision ID: fa2b6a691855
Revises: 4d3fb6d39a23
Create Date: 2025-02-14 11:49:11.057621

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fa2b6a691855'
down_revision = '4d3fb6d39a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
