# Use the official Node.js image as the base image
FROM oven/bun:alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json (or yarn.lock)
COPY package.json package-lock.json* ./

# Install dependencies
RUN bun install

# Install bash
RUN apk add --no-cache bash

# Copy the rest of your app's source code
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# Command to run the app in development mode
CMD ["bun", "run", "dev", "--turbo"]
# CMD ["bun", "run", "dev"]
