services:

  # db:
  #   restart: "no"
  #   ports:
  #     - "5432:5432"

  adminer:
    restart: "no"
    ports:
      - "8080:8080"

  backend:
    restart: "no"
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/app
    build:
      context: ./backend
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    # command: sleep infinity  # Infinite loop to keep container alive doing nothing
    command: /start-reload.sh

  frontend:
    restart: "no"
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        - NODE_ENV=development
        - NEXT_PUBLIC_API_URL=http://backend:4322

networks:
  traefik-public:
    # For local dev, don't expect an external Traefik network
    external: false