# Generated by Django 4.2.5 on 2023-10-11 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newssource_category_newssource_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newssource'),
        ),
    ]
