from django.db import models


class Vorgang(models.Model):
    id = models.IntegerField(primary_key=True)
    beratungsstand = models.CharField(max_length=100)
    vorgangstyp = models.CharField(max_length=100)
    wahlperiode = models.IntegerField()
    initiative = models.CharField(max_length=100)
    datum = models.DateField()
    aktualisiert = models.DateTimeField()
    titel = models.TextField()
    abstract = models.TextField(blank=True, null=True)
    sachgebiet = models.CharField(max_length=100, blank=True, null=True)
    deskriptor = models.CharField(max_length=100, blank=True, null=True)
    gesta = models.CharField(max_length=100, blank=True, null=True)
    zustimmungsbeduerftigkeit = models.CharField(max_length=100, blank=True, null=True)
    kom = models.CharField(max_length=100, blank=True, null=True) 
    ratsdok = models.CharField(max_length=100, blank=True, null=True)
    verkuendung = models.CharField(max_length=100, blank=True, null=True)
    inkrafttreten = models.DateField(blank=True, null=True)
    archiv = models.CharField(max_length=100, blank=True, null=True)
    mitteilung = models.TextField(blank=True, null=True)
    vorgang_verlinkung = models.IntegerField(blank=True, null=True)
    sek = models.CharField(max_length=100, blank=True, null=True)
    url = models.URLField(blank=True, null=True)

class Vorgangsposition(models.Model):
    id = models.IntegerField(primary_key=True)
    vorgangsposition = models.CharField(max_length=100)
    zuordnung = models.CharField(max_length=2)
    gang = models.BooleanField()
    fortsetzung = models.BooleanField()
    nachtrag = models.BooleanField()
    vorgangstyp = models.CharField(max_length=100)
    titel = models.CharField(max_length=200)
    dokumentart = models.CharField(max_length=20)
    vorgang = models.ForeignKey(Vorgang, on_delete=models.CASCADE)
    datum = models.DateField()
    aktualisiert = models.DateTimeField()
    fundstelle = models.CharField(max_length=100)
    urheber = models.CharField(max_length=100)
    ueberweisung = models.CharField(max_length=100)
    aktivitaet_anzeige = models.CharField(max_length=100)
    aktivitaet_anzahl = models.IntegerField()
    ressort = models.CharField(max_length=100)
    beschlussfassung = models.CharField(max_length=100, blank=True, null=True)
    ratsdok = models.CharField(max_length=100, blank=True, null=True)
    kom = models.CharField(max_length=100, blank=True, null=True)
    sek = models.CharField(max_length=100, blank=True, null=True)
    mitberaten = models.IntegerField(blank=True, null=True)
    abstract = models.TextField(blank=True, null=True)

class Drucksache(models.Model):
    id = models.IntegerField(primary_key=True)
    drucksachetyp = models.CharField(max_length=100)
    dokumentart = models.CharField(max_length=20)
    dokumentnummer = models.CharField(max_length=20)
    wahlperiode = models.IntegerField()
    herausgeber = models.CharField(max_length=2)
    datum = models.DateField()
    aktualisiert = models.DateTimeField() 
    titel = models.TextField()
    autoren_anzeige = models.CharField(max_length=100)
    autoren_anzahl = models.IntegerField()
    fundstelle = models.CharField(max_length=100)
    pdf_hash = models.CharField(max_length=32, blank=True, null=True)
    urheber = models.CharField(max_length=100)
    vorgangsbezug = models.IntegerField(blank=True, null=True)
    vorgangsbezug_anzahl = models.IntegerField()
    ressort = models.CharField(max_length=100)
    anlagen = models.TextField(blank=True, null=True)

class Plenarprotokoll(models.Model):
    id = models.IntegerField(primary_key=True)
    dokumentart = models.CharField(max_length=20)
    dokumentnummer = models.CharField(max_length=20)
    wahlperiode = models.IntegerField()
    herausgeber = models.CharField(max_length=2)
    datum = models.DateField()
    aktualisiert = models.DateTimeField()
    titel = models.TextField()
    fundstelle = models.CharField(max_length=100)
    pdf_hash = models.CharField(max_length=32, blank=True, null=True)
    vorgangsbezug = models.IntegerField(blank=True, null=True)
    vorgangsbezug_anzahl = models.IntegerField()
    sitzungsbemerkung = models.CharField(max_length=100, blank=True, null=True)

class Aktivitaet(models.Model):
    id = models.IntegerField(primary_key=True)
    aktivitaetsart = models.CharField(max_length=100)
    dokumentart = models.CharField(max_length=20)  
    wahlperiode = models.IntegerField()
    datum = models.DateField()
    aktualisiert = models.DateTimeField()
    titel = models.TextField()
    fundstelle = models.CharField(max_length=100)
    vorgangsbezug = models.IntegerField(blank=True, null=True)
    vorgangsbezug_anzahl = models.IntegerField()
    deskriptor = models.CharField(max_length=100, blank=True, null=True)
    abstract = models.TextField(blank=True, null=True)

class Person(models.Model):
    id = models.IntegerField(primary_key=True)
    nachname = models.CharField(max_length=100)
    vorname = models.CharField(max_length=100) 
    namenszusatz = models.CharField(max_length=20, blank=True, null=True)
    wahlperiode = models.IntegerField()
    basisdatum = models.DateField()
    datum = models.DateField()
    aktualisiert = models.DateTimeField()
    titel = models.TextField()
    person_roles = models.CharField(max_length=100, blank=True, null=True)