"""Add classification_schemes table

Revision ID: cd4e15127706
Revises: f2a3580fe700
Create Date: 2025-01-28 03:17:23.220978

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cd4e15127706'
down_revision = 'f2a3580fe700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classificationscheme', 'prompt',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('classificationscheme', 'input_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classificationscheme', 'input_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('classificationscheme', 'prompt',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
