"""Add workspaces table

Revision ID: edf0e72eca58
Revises: 39603fcfa2f0
Create Date: 2025-01-27 21:26:45.382306

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'edf0e72eca58'
down_revision = '39603fcfa2f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sources', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('user_id_ownership', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id_ownership'], ['user.id'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspace')
    # ### end Alembic commands ###
