apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.postgres.image }}:{{ .Values.image.postgres.tag }}"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.postgresqlDatabase }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.postgresqlUser }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgres.postgresqlPassword }}"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          emptyDir: {}