# traefik.yml
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

http:
  routers:
    geojson:
      rule: "PathPrefix(`/api/v1/geojson`)"
      service: geo_service
      entryPoints:
        - http
    geojson_events:
      rule: "PathPrefix(`/api/v1/geojson_events`)"
      service: geo_service
      entryPoints:
        - http

  services:
    geo_service:
      loadBalancer:
        servers:
          - url: "http://geo_service:3690"

providers:
  docker: {}
  file:
    filename: /etc/traefik/traefik.yml

certificatesResolvers:
  le:
    acme:
      email: ${EMAIL}
      storage: /certificates/acme.json
      tlsChallenge: {}
